/*
 * DeskletConfigPanel.java
 *
 * Created on 29 December 2007, 22:53
 */
package lh.worldclock.desklet;

import lh.worldclock.WorldClockPanel;
import org.glossitope.desklet.DeskletContainer;

/**
 *
 * @author  Ludovic
 */
public class DeskletConfigPanel extends javax.swing.JPanel
{
  private DeskletContainer container = null;
  private WorldClockPanel worldClockPane = null;

  /** Creates new form DeskletConfigPanel */
  public DeskletConfigPanel()
  {
    initComponents();
    btnApply.setVisible(false);
  }
  
  public void destroy()
  {
    if (container != null)
    {
      container = null;
    }
    if (worldClockPane != null)
    {
      worldClockPane = null;
    }
  }
  
  public void setConfigPath(String path)
  {
    configPanel.setConfigPath(path);
  }
  
  public void setContainer(DeskletContainer container)
  {
    this.container = container;
  }
  
  public void setWorldClockPane(WorldClockPanel worldClockPane)
  {
    this.worldClockPane = worldClockPane;
  }
  
  public String getConfigPath()
  {
    return configPanel.getConfigPath();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    configPanel = new lh.worldclock.ConfigPanel();
    btnApply = new javax.swing.JButton();
    btnClose = new javax.swing.JButton();

    btnApply.setText("Apply");
    btnApply.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        apply(evt);
      }
    });

    btnClose.setText("Close");
    btnClose.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        close(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(btnApply)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnClose))
          .addComponent(configPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(configPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnApply)
          .addComponent(btnClose))
        .addContainerGap())
    );
  }// </editor-fold>//GEN-END:initComponents

  private void apply(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apply
//    if (worldClockPane != null)
//    {
//      worldClockPane.loadConfig(configPanel.getConfigPath());
//    }
  }//GEN-LAST:event_apply

  private void close(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close
    if (container != null)
    {
      container.setVisible(false);
    }
  }//GEN-LAST:event_close

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnApply;
  private javax.swing.JButton btnClose;
  private lh.worldclock.ConfigPanel configPanel;
  // End of variables declaration//GEN-END:variables
}
